const themes = {
  default: {
    0: {
      id: 0,
      name: "Bom",
      image: "/default/bom.png",
      wins: [1, 2, 4, 5, 6, 7, 8, 9, 10],
      loses: [3],
      canTouch: false,
      amount: 1,
      numberVisible: false,
    },
    1: {
      id: 1,
      name: "Spion",
      image: "/default/spion.png",
      wins: [10],
      loses: [0, 2, 3, 4, 5, 6, 7, 8, 9],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    2: {
      id: 2,
      name: "Verkenner",
      image: "/default/verkenner.png",
      wins: [1],
      loses: [0, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 8,
      numberVisible: true,
    },
    3: {
      id: 3,
      name: "Mineur",
      image: "/default/mineur.png",
      wins: [0, 1, 2],
      loses: [4, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    4: {
      id: 4,
      name: "Sergeant",
      image: "/default/sergeant.png",
      wins: [1, 2, 3],
      loses: [0, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 5,
      numberVisible: true,
    },
    5: {
      id: 5,
      name: "Luitenant",
      image: "/default/luitenant.png",
      wins: [1, 2, 3, 4],
      loses: [0, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    6: {
      id: 6,
      name: "Kapitein",
      image: "/default/kapitein.png",
      wins: [1, 2, 3, 4, 5],
      loses: [0, 7, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    7: {
      id: 7,
      name: "Majoor",
      image: "/default/majoor.png",
      wins: [1, 2, 3, 4, 5, 6],
      loses: [0, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    8: {
      id: 8,
      name: "Kolonel",
      image: "/default/kolonel.png",
      wins: [1, 2, 3, 4, 5, 6, 7],
      loses: [0, 9, 10],
      canTouch: true,
      amount: 3,
      numberVisible: true,
    },
    9: {
      id: 9,
      name: "Generaal",
      image: "/default/generaal.png",
      wins: [1, 2, 3, 4, 5, 6, 7, 8],
      loses: [0, 10],
      canTouch: true,
      amount: 2,
      numberVisible: true,
    },
    10: {
      id: 10,
      name: "Maarschalk",
      image: "/default/maarschalk.png",
      wins: [2, 3, 4, 5, 6, 7, 8, 9],
      loses: [0, 1],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    99: {
      id: 99,
      name: "Vlag",
      image: "/default/vlag.png",
      wins: [],
      loses: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: false,
      amount: 1,
      numberVisible: false,
    },
  },
  disney: {
    0: {
      id: 0,
      name: "Mickey Mouse's Tovenaars Hoed",
      image: "/disney/mickey-mouses-sorcerers-hats.png",
      wins: [1, 2, 4, 5, 6, 7, 8, 9, 10],
      loses: [3],
      canTouch: false,
      amount: 1,
      numberVisible: false,
    },
    1: {
      id: 1,
      name: "Tinkerbel",
      image: "/disney/tinker-bell.png",
      wins: [10],
      loses: [0, 2, 3, 4, 5, 6, 7, 8, 9],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    2: {
      id: 2,
      name: "Peter Pan",
      image: "/disney/peter-pan.png",
      wins: [1],
      loses: [0, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 8,
      numberVisible: true,
    },
    3: {
      id: 3,
      name: "Dagobert Duck",
      image: "/disney/dagobert-duck.png",
      wins: [0, 1, 2],
      loses: [4, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    4: {
      id: 4,
      name: "Aladdin",
      image: "/disney/aladdin.png",
      wins: [1, 2, 3],
      loses: [0, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 5,
      numberVisible: true,
    },
    5: {
      id: 5,
      name: "Buzz Lightyear",
      image: "/disney/buzz-lightyear.png",
      wins: [1, 2, 3, 4],
      loses: [0, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    6: {
      id: 6,
      name: "Raya",
      image: "/disney/raya.png",
      wins: [1, 2, 3, 4, 5],
      loses: [0, 7, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    7: {
      id: 7,
      name: "Maui",
      image: "/disney/maui.png",
      wins: [1, 2, 3, 4, 5, 6],
      loses: [0, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    8: {
      id: 8,
      name: "Elsa",
      image: "/disney/elsa.png",
      wins: [1, 2, 3, 4, 5, 6, 7],
      loses: [0, 9, 10],
      canTouch: true,
      amount: 3,
      numberVisible: true,
    },
    9: {
      id: 9,
      name: "Simba",
      image: "/disney/simba.png",
      wins: [1, 2, 3, 4, 5, 6, 7, 8],
      loses: [0, 10],
      canTouch: true,
      amount: 2,
      numberVisible: true,
    },
    10: {
      id: 10,
      name: "Mickey Mouse",
      image: "/disney/mickey-mouse.png",
      wins: [2, 3, 4, 5, 6, 7, 8, 9],
      loses: [0, 1],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    99: {
      id: 99,
      name: "Assepoester's Glazen Muiltje",
      image: "/disney/cinderellas-glass-slipper.png",
      wins: [],
      loses: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: false,
      amount: 1,
      numberVisible: false,
    },
  },
  studio100: {
    0: {
      id: 0,
      name: "Plopkoeken",
      image: "/studio100/plopkoeken.jpg",
      wins: [1, 2, 4, 5, 6, 7, 8, 9, 10],
      loses: [3],
      canTouch: false,
      amount: 1,
      numberVisible: false,
    },
    1: {
      id: 1,
      name: "Kabouter Plop",
      image: "/studio100/plop.png",
      wins: [10],
      loses: [0, 2, 3, 4, 5, 6, 7, 8, 9],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    2: {
      id: 2,
      name: "Gamekeeper",
      image: "/studio100/gamekeepers.png",
      wins: [1, 3, 4, 5, 6, 7, 8, 9, 10],
      loses: [0],
      canTouch: true,
      amount: 8,
      numberVisible: true,
    },
    3: {
      id: 3,
      name: "Piet Piraat",
      image: "/studio100/piet-piraat.png",
      wins: [0, 1, 2],
      loses: [4, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    4: {
      id: 4,
      name: "K3",
      image: "/studio100/k3.png",
      wins: [1, 2, 3],
      loses: [0, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 5,
      numberVisible: true,
    },
    5: {
      id: 5,
      name: "Bumba",
      image: "/studio100/bumba.png",
      wins: [1, 2, 3, 4],
      loses: [0, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    6: {
      id: 6,
      name: "Mega Mindy",
      image: "/studio100/mega-mindy.png",
      wins: [1, 2, 3, 5],
      loses: [0, 4, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    7: {
      id: 7,
      name: "Maya de Bij",
      image: "/studio100/maya-de-bij.png",
      wins: [1, 2, 3, 4, 5, 6],
      loses: [0, 8, 9, 10],
      canTouch: true,
      amount: 4,
      numberVisible: true,
    },
    8: {
      id: 8,
      name: "Nachtwacht",
      image: "/studio100/nachtwacht.png",
      wins: [1, 2, 3, 4, 5, 6, 7],
      loses: [0, 9, 10],
      canTouch: true,
      amount: 3,
      numberVisible: true,
    },
    9: {
      id: 9,
      name: "Samson",
      image: "/studio100/samson.png",
      wins: [1, 2, 3, 4, 5, 6, 7, 8],
      loses: [0, 10],
      canTouch: true,
      amount: 2,
      numberVisible: true,
    },
    10: {
      id: 10,
      name: "Freddy",
      image: "/studio100/100-wolf.png",
      wins: [2, 3, 4, 5, 6, 7, 8, 9],
      loses: [0, 1],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    99: {
      id: 99,
      name: "K3 Brooddoos",
      image: "/studio100/k3-brooddoos.jpg",
      wins: [],
      loses: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: false,
      amount: 1,
      numberVisible: false,
    },
  },
  pirates: {
    0: {
      id: 0,
      name: "Kanonskogels",
      image: "/pirates/kanonskogels.png",
      wins: [],
      loses: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: false,
      amount: 6,
      numberVisible: false,
    },
    1: {
      id: 1,
      name: "Elizabeth Swann",
      image: "/pirates/elizabeth-swann.png",
      wins: [6],
      loses: [2, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    2: {
      id: 2,
      name: "Jan Haring",
      image: "/pirates/jan-haring.png",
      wins: [1, 10],
      loses: [3, 4, 5, 6, 7, 8, 9],
      canTouch: true,
      amount: 8,
      numberVisible: true,
    },
    3: {
      id: 3,
      name: "Joshamee Gibbs",
      image: "/pirates/joshamee-gibbs.png",
      wins: [2, 9, 10],
      loses: [4, 5, 6, 7, 8],
      canTouch: true,
      amount: 5,
      numberVisible: true,
    },
    4: {
      id: 4,
      name: "Zwartbaard",
      image: "/pirates/zwartbaard.png",
      wins: [3, 8, 9, 10],
      loses: [5, 6, 7],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    5: {
      id: 5,
      name: "Red Rackham",
      image: "/pirates/red-rackham.webp",
      wins: [4, 7, 8, 9, 10],
      loses: [6],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    6: {
      id: 6,
      name: "Piet Piraat",
      image: "/pirates/piet-piraat.png",
      wins: [5, 6, 7, 8, 9, 10],
      loses: [7],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    7: {
      id: 7,
      name: "Kapitein Haak",
      image: "/pirates/kapitein-haak.png",
      wins: [6, 7, 8, 9, 10],
      loses: [1, 2, 3, 4, 5],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    8: {
      id: 8,
      name: "Davy Jones",
      image: "/pirates/davy-jones.png",
      wins: [7, 8, 9, 10],
      loses: [1, 2, 3, 4],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    9: {
      id: 9,
      name: "Captain Hector Barbossa",
      image: "/pirates/captain-hector-barbossa.png",
      wins: [8, 9, 10],
      loses: [1, 2, 3, 4, 5],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    10: {
      id: 10,
      name: "Captain Jack Sparrow",
      image: "/pirates/captain-jack-sparrow.png",
      wins: [9, 10],
      loses: [1, 2, 3, 4, 5, 6, 7, 8],
      canTouch: true,
      amount: 1,
      numberVisible: true,
    },
    99: {
      id: 99,
      name: "Jolly Roger",
      image: "/pirates/jolly-roger.png",
      wins: [],
      loses: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      canTouch: false,
      amount: 1,
      numberVisible: false,
    },
  },
};

const list = [
  {
    value: "default",
    label: "Standaard",
  },
  {
    value: "studio100",
    label: "Studio 100",
  },
  {
    value: "disney",
    label: "Disney",
  },
  {
    value: "pirates",
    label: "Piraten",
  },
];

const cantBeDeleted = [0, 99];

const defaultCard = (cards, id) => {
  return {
    id: id,
    name: "",
    image: "",
    wins: [...Object.values(cards)]
      .filter((card) => card.id !== 99)
      .map((card) => card.id),
    loses: [],
    canTouch: true,
    amount: null,
    numberVisible: true,
  };
};

export { themes, list, cantBeDeleted, defaultCard };
